<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite skipped="0" hostname="CWJShen" name="com.revature.TestOverview" tests="4" failures="1" timestamp="27 Jan 2018 19:46:44 GMT" time="6.258" errors="0">
  <testcase name="feature" time="0.008" classname="com.revature.TestOverview"/>
  <testcase name="feature" time="0.001" classname="com.revature.TestOverview"/>
  <testcase name="TestOne" time="3.153" classname="com.revature.TestOverview">
    <failure type="java.lang.AssertionError" message="CSV button/ filter button not found. Not in Overview tab">
      <![CDATA[java.lang.AssertionError: CSV button/ filter button not found. Not in Overview tabat org.testng.Assert.fail(Assert.java:96)at com.revature.TestOverview.TestOne(TestOverview.java:49)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- TestOne -->
  <testcase name="TestTwo" time="3.096" classname="com.revature.TestOverview"/>
=======
<testsuite hostname="DESKTOP-MDC2CVU" failures="0" tests="4" name="com.revature.TestOverview" time="6.418" errors="0" timestamp="27 Jan 2018 20:32:57 GMT" skipped="0">
  <testcase classname="com.revature.TestOverview" name="feature" time="0.004"/>
  <testcase classname="com.revature.TestOverview" name="TestOne" time="3.244"/>
  <testcase classname="com.revature.TestOverview" name="feature" time="0.011"/>
  <testcase classname="com.revature.TestOverview" name="TestTwo" time="3.159"/>
>>>>>>> antoniomdotson
</testsuite> <!-- com.revature.TestOverview -->
