<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="CWJShen" name="com.revature.TrainerSuite" tests="3" failures="0" timestamp="26 Jan 2018 20:22:02 GMT" time="0.461" errors="2">
  <testcase name="setUpClass" time="0.461" classname="com.revature.TrainerSuite">
    <error type="cucumber.runtime.DuplicateStepDefinitionException" message="Duplicate step definitions in com.revature.cuketests.LocationsCukes.loggedAsTrainer(WebDriver) in file:/C:/Users/Jason/Documents/GitHub/TA_Framework/TA_Framework_Maven/target/classes/ and com.revature.cuketests.OverviewCukes.loggedAsTrainer(WebDriver) in file:/C:/Users/Jason/Documents/GitHub/TA_Framework/TA_Framework_Maven/target/classes/">
      <![CDATA[cucumber.runtime.DuplicateStepDefinitionException: Duplicate step definitions in com.revature.cuketests.LocationsCukes.loggedAsTrainer(WebDriver) in file:/C:/Users/Jason/Documents/GitHub/TA_Framework/TA_Framework_Maven/target/classes/ and com.revature.cuketests.OverviewCukes.loggedAsTrainer(WebDriver) in file:/C:/Users/Jason/Documents/GitHub/TA_Framework/TA_Framework_Maven/target/classes/at cucumber.runtime.RuntimeGlue.addStepDefinition(RuntimeGlue.java:33)at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:151)at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:68)at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:41)at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:86)at cucumber.runtime.Runtime.<init>(Runtime.java:92)at cucumber.runtime.Runtime.<init>(Runtime.java:70)at cucumber.runtime.Runtime.<init>(Runtime.java:66)at cucumber.api.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:42)at cucumber.api.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:16)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- setUpClass -->
  <testcase name="feature" time="0.000" classname="com.revature.TrainerSuite">
    <skipped/>
  </testcase> <!-- feature -->
  <testcase name="tearDownClass" time="0.000" classname="com.revature.TrainerSuite">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat cucumber.api.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:34)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:208)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- tearDownClass -->
</testsuite> <!-- com.revature.TrainerSuite -->
